default['chef_client']['cron']['minutes'] = '*/5'

case node['platform_family']
when 'rhel'
  default['chef_client_migration']['validation_pem_location'] = '/etc/chef/validation.pem'
  default['chef_client_migration']['move_files_script'] = '/usr/local/bin/move_old_linux_files'
  default['chef_client_migration']['client_rb'] = '/etc/chef/client.rb'
  default['chef_client_migration']['client_rb_template'] = 'linux_client_rb.erb'
  default['chef_client_migration']['move_files_cmd'] = 'move_old_linux_files'
  default['chef_client_migration']['move_old_chef_dir'] = '/bin/mv -v /etc/chef /etc/chef_$(date +%s)'
  default['chef_client_migration']['default_chef_path'] = '/etc/chef'
when 'windows'
  default['chef_client_migration']['validation_pem_location'] = 'c:\\chef\\validation.pem'
  default['chef_client_migration']['move_files_script'] = 'c:\\chef\\move_old_windows_files.bat'
  default['chef_client_migration']['client_rb'] = 'c:\\chef\\client.rb'
  default['chef_client_migration']['client_rb_template'] = 'windows_client_rb.erb'
  default['chef_client_migration']['move_files_cmd'] = 'move_old_windows_files.bat'
  default['chef_client_migration']['move_old_chef_dir'] = 'move /y c:\chef c:\chef_legacy'
  default['chef_client_migration']['default_chef_path'] = 'c:\\chef'
when 'debian'
  default['chef_client_migration']['validation_pem_location'] = '/etc/chef/validation.pem'
  default['chef_client_migration']['move_files_script'] = '/usr/local/bin/move_old_linux_files'
  default['chef_client_migration']['client_rb'] = '/etc/chef/client.rb'
  default['chef_client_migration']['client_rb_template'] = 'linux_client_rb.erb'
  default['chef_client_migration']['move_files_cmd'] = 'move_old_linux_files'
  default['chef_client_migration']['move_old_chef_dir'] = '/bin/mv -v /etc/chef /etc/chef_$(date +%s)'
  default['chef_client_migration']['default_chef_path'] = '/etc/chef'
end

